---
triple:          'arm64-apple-darwin'
binary-path:     A
relocations:
  - { offsetInCU: 0x26, offset: 0x26, size: 0x8, addend: 0x0, symName: _inputArray, symObjAddr: 0x0, symBinAddr: 0x100003A80, symSize: 0x7C }
  - { offsetInCU: 0x41, offset: 0x41, size: 0x8, addend: 0x0, symName: _inputArray, symObjAddr: 0x0, symBinAddr: 0x100003A80, symSize: 0x7C }
  - { offsetInCU: 0xAB, offset: 0xAB, size: 0x8, addend: 0x0, symName: _sortFlowers, symObjAddr: 0x7C, symBinAddr: 0x100003AFC, symSize: 0x168 }
  - { offsetInCU: 0x123, offset: 0x123, size: 0x8, addend: 0x0, symName: _inputFlowers, symObjAddr: 0x1E4, symBinAddr: 0x100003C64, symSize: 0x10C }
  - { offsetInCU: 0x162, offset: 0x162, size: 0x8, addend: 0x0, symName: _test, symObjAddr: 0x2F0, symBinAddr: 0x100003D70, symSize: 0x12C }
  - { offsetInCU: 0x1CC, offset: 0x1CC, size: 0x8, addend: 0x0, symName: _f, symObjAddr: 0x41C, symBinAddr: 0x100003E9C, symSize: 0x70 }
  - { offsetInCU: 0x1FE, offset: 0x1FE, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x48C, symBinAddr: 0x100003F0C, symSize: 0x2C }
...
